### ISSUE TITLE
Edit project settings to point web page at https://dzenanr.github.io/order/

### ISSUE THREAD

**Issue by kevmoo** [dzenanr/order#2]
Easier to find :smile:

**Comment by dzenanr** [comment]
What project?
https://github.com/dzenanr/order
or
http://dzenanr.github.io/order/

I already have a link to http://dzenanr.github.io/order/ in README.md of https://github.com/dzenanr/order.

I suppose a link should go to the game so that anyone can play it within http://dzenanr.github.io/order/. However, I cannot find the game code in the executable form. I still have a hard time to understand what peanut actually does for me. Well, I am 62 years old developer.

**Comment by dzenanr** [comment]
I think I get it now. I had already created GitHub Page for the order game and was looking for something else.

**Comment by kevmoo** [comment]
No worries.

I was expecting you run `peanut` in your project and do a `git push origin gh-pages:gh-pages` to publish the game on `http://dzenanr.github.io/order/`

Then you can click on the project setting in GitHub – above the file list – to set the web page so it's easy to find/play.

**Comment by dzenanr** [comment]
added link to
http://dzenanr.github.io/order
from
https://github.com/dzenanr/order

added link to
http://learningdart.org/app/order/
from
http://dzenanr.github.io/order
in order to play the game

**Comment by dzenanr** [comment]
replaced
http://learningdart.org/app/order/
with
http://dzenanr.github.io/order/web/

**Comment by kevmoo** [comment]
If you're happy with peanut, please share on G+, twitter, etc. :-)

On Thu, Apr 16, 2015 at 4:46 PM, Dzenan Ridjanovic <notifications@github.com

**Comment by dzenanr** [comment]
Hi Kevin,

I have tried peanut with another project, attract, and git could not be
found again:

https://github.com/dzenanr/attract/issues/1

Dzenan
